let products = [
    {
        id: 1001,
        title: "Maths Classes",
        description: "<em>Extra curriculum classes</em>",
        price: 40,
        image: "../images/maths.jpg",
        availableInventory: 10,
        rating: 4,
    },
    {
        id: 1001,
        title: "Football",
        description: "<em>Extra curriculum classes</em>",
        price: 6,
        image: "../images/‪football.jpg",
        availableInventory: 10,
        rating: 4,
    },
    {
        id: 1001,
        title: "Homework Club",
        description: "<em>Extra curriculum classes</em>",
        price: 25,
        image: "../images/homework-club.jpg",
        availableInventory: 10,
        rating: 2,
    },
    {
        id: 1001,
        title: "Survival Skills",
        description: "<em>Extra curriculum classes</em>",
        price: 15,
        image: "../images/survival-skills.jpg",
        availableInventory: 10,
        rating: 5,
    },
    {
        id: 1001,
        title: "Drama and Music",
        description: "<em>Extra curriculum classes</em>",
        price: 3,
        image: "../images/‪drama-music.jpg",
        availableInventory: 10,
        rating: 3,
    },
]